### ISSUE TITLE
Unintelligible places in the code

### ISSUE THREAD

**Issue by l291351760** [tharaj90/OTFS-MRC-detection-MATLAB-package#1]
Hi,

I am very happy to find your code. But when I generated the time-frequency domain channel matrix, I didn't understand why the diagonal elements are taken in the code. Can you tell me why?
H_t_f(n,1:M)=diag(Fm*Gn*Fm').';%%Didn't understand why the diagonal elements are taken in the code

best,
kun

**Comment by l291351760** [comment]
I didn’t understand the conversion from time domain to time-frequency domain

**Comment by tharaj90** [comment]
Hi,

> m very happy to find your code. But when I generated the time-frequency domain channel matrix, I didn't understand why the diagonal elements are taken in the code. Can you tell me why?
> H_t_f(n,1:M)=diag(Fm_Gn_Fm').';%%Didn't understand why the diagonal elements are taken in the code




Only diagonal elements of the time-frequency channel matrix are used for the initial estimates, which is similar to the single tap equalizer for OFDM. The purpose here is simply to compute a rough estimate of the transmitted symbols to use as an initial estimate for the MRC detector, so we ignore the non-diagonal elements (i.e., the elements corresponding to inter-carrier interference are ignored). 

If we consider the non-diagonal elements, then the complexity of the time-freq domain equalizer becomes high. That is why we ignore the non-diagonal elements.

**Comment by l291351760** [comment]
Wow, it turned out to be so, thank you for your reply, I wish you good health and all the best
